config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/pages/home"
  get "/about" =>  "pages#about", as: :about
   get "/help" =>  "pages#help", as: :help

  get "/my-posts" => "users#my_posts", as: :my_posts
  patch "/load-blog/:id" => "users#load_blog", as: :load_blog
  get "/invite/:id" => "roles#show", as: :invite
  patch "/invite/:id/deny" => "roles#deny_invite", as: :deny_invite
  get "/invite/:id/accept" => "roles#accept_invite", as: :accept_invite
  get "/register" => "users#new", as: :register
  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create", as: :sessions
  get "/config" => "users#edit", as: :config
  post "blogs/:blog_id/roles/:id"   => "roles#update"
  patch "/password_resets/:id/edit" => "password_resets#update", as: :password_reset

  resources :sessions, only: [:new, :create]
  resources :users, only: [:create, :index, :update, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :blogs do
    resources :roles, only: [:new, :show, :update, :create, :destroy]
    resources :posts
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	extend FriendlyId
	  friendly_id :slug_candidates, use: :slugged

	has_many :blogs
	has_many :posts
	has_many :roles, dependent: :destroy
	
	validates :first_name, :last_name, presence: true
	validates :email, presence: true,
					  uniqueness: true,
					  format: {
					  		with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create 
					  }
	before_save :downcase_email
	 validate :is_valid_email?, on: :create
	
	  # for ranking
	  MULTIPLIERS = {
	    recent_post: 4,
	    active_user_on_blogs: 3,
	    amount_of_posts_made: 3,
	    recent_blog: 2,
	    amount_of_blogs: 1
	  }


	 def slug_candidates
	    [
	      :full_name,
	      [:full_name, :id]
	    ]
  	end

	def should_generate_new_friendly_id?
    	first_name_changed? || last_name_changed?
  	end

	def downcase_email
		self.email =  email.downcase
	end
	def generate_password_reset_token!
		update_attribute(:password_reset_token, SecureRandom.urlsafe_base64(48))
	end

	def is_valid_email? 
		 return unless errors.blank?
		if !User::is_valid_email? self.email
			errors.add :email, "The email you entered is not valid."
		end
	end
	
	def self.is_valid_email? email

    	 response = HTTP.get "https://api:pubkey-6b5o0r4clsvspjv0m2cc87shki3o1fg8"\
"@api.mailgun.net/v2/address/validate", :params =>{ :address => email }
		json = JSON.parse(response)
		puts json
		if (json["is_valid"]!=nil)
			 json["is_valid"]
		else
			false
		end
	end

	 def self.ranked_users
	    @users = User.all
	    @ranks = {};
	    @sorted_users = @users.sort_by do |u|
	      roles = Role.where(:user_id => u.id, :active => 1)
	      posts = Post.where(:user_id => u.id, :published => true)
	      blogs = Blog.where(:user_id => u.id)
	      last_5_posts = Post.last(5)
	      rank = 0
	      # recent post
	      intersection = posts & last_5_posts;
	      rank += self::MULTIPLIERS[:recent_post] * intersection.count
	      puts rank
	      # active users
	      rank += self::MULTIPLIERS[:active_user_on_blogs] * roles.count
	      puts rank
	      # amount of posts
	      rank +=  self::MULTIPLIERS[:amount_of_posts_made] * posts.count    
	      # recent blog
	       intersection = blogs & last_5_posts;
	       rank += self::MULTIPLIERS[:recent_blog] * intersection.count
	      # amount of blogs
	      puts u.full_name + " = "+rank.to_s
	      rank += self::MULTIPLIERS[:amount_of_blogs] *blogs.count
	      rank
	    end

	    @sorted_users.reverse
	  end

	def full_name
		self.first_name+" "+self.last_name
	end

	def gravatar_url
		"http://gravatar.com/avatar/"+Digest::MD5.hexdigest(email.strip.downcase)+"?d=mm"
	end

	def self.gravatar_url email
		"http://gravatar.com/avatar/"+Digest::MD5.hexdigest(email.strip.downcase)+"?d=mm"
	end

	def all_roles
		allBlogs = [];
		Role.where(user_id: self.id, active: 1).each do |role|
			if is_blog_member? role.blog_id 
				allBlogs.push role
			end
		end
		allBlogs
	end

	def is_creator? id=self.current_blog_id
		 current_role == Role::CREATOR
	end

	def can_edit_role? role
		blog = role.blog
		editorRole = self.get_role blog
		if role && blog
			editorRole && (editorRole.role>role.role || ( editorRole==role && role!=Role::CREATOR))
		else
			false
		end
	end

	def can_edit_post? post
		if post.user
			authorRole = post.user.get_role post.blog
			editorRole = self.get_role post.blog
			if authorRole==nil && editorRole.role>=Role::MODERATOR 
				# probably means author was deleted so moderators and contributors can edit these
				return true 
			end
			authorRole && editorRole && (editorRole.role>authorRole.role || self.is_creator?(post.blog) || editorRole==authorRole)
		else
			true
		end
	end

	def current_role
		 if is_blog_member?
			#blog should be scoped to user so we find role
			Role.where(blog_id: current_blog.id, user_id: self.id, active: 1).first.role
		end
	end

	def current_role_text
		role = current_role
		if role
			Role::ROLE_TEXT[role]
		end
	end

	def get_role blog
		if is_blog_member? blog.id
			Role.where(blog_id: blog.id, user_id: self.id, active: 1).first
		end
	end

	#check if blog exists and then if user has a role
	def is_blog_member? id=self.current_blog_id
		 Blog.exists?(id) && Role.exists?(
		 		blog_id: id, 
		 		user_id: self.id, 
		 		active: 1)
			
	end

	def has_open_invites?
		Role.exists?(
			email: self.email,
			active: 0)

	end

	def open_invites_count 
		Role.where(
			email: self.email,
			active: 0).count 
	
	end

	def open_invites
		Role.where(
			email: self.email,
			active: 0)
	end

	def current_blog
		# we need to grab current blog here
		# something like Blog.find(self.current_blog_id)
		# validate that you still have permissions, if not set to nil
		if is_blog_member?
		 	Blog.find(self.current_blog_id)
		else
			update_attribute(:current_blog_id, nil) if self.current_blog_id!=nil
			return nil
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_filter :store_location, only: [:edit, :my_posts]
	before_filter :require_user, only: [:edit, :my_posts]
	respond_to :json, only: [:update]

	def new
		@user =User.new
		@email = params[:email]||nil
	end

	def show
		@user = User.friendly.find(params[:id])
	end

	def index
		@users = User::ranked_users
	end
	

	def create
		@user = User.new(user_params)

		respond_to do |format|
		  if @user.save
		    session[:user_id] = @user.id
		    flash[:success] = "Thanks for signing up!"
		    format.html { redirect_to session[:return_to]||new_blog_path, success: "Thanks for signing up!" }
		    format.json { render :show, status: :created, location: @user }
		  else
		    format.html { render :new }
		    format.json { render json: @user.errors, status: :unprocessable_entity }
		  end
		end
	end

	def load_blog
		if current_user.is_blog_member? params[:id] 
			current_user.update_attribute(:current_blog_id,params[:id])
			flash[:notice] = "Successfully loaded '#{current_user.current_blog.title}'"
		else
			blog = Blog.find(params[:id])
			flash[:error] = "Could not load '#{blog.title}'. Sorry."
		end
		redirect_to config_path
	end

	def update
	  respond_to do |format|
	    if current_user.update(user_params)
	       msg = { :status => "ok", :message => "Success!" }
	      format.json { render :json => msg }
	    else
	      format.json { render json: {:model => current_user.reload, :errors => current_user.errors}, status: :unprocessable_entity }
	    end
	  end
	end

	def my_posts
		# first get current blog
		@blog = current_user.current_blog if current_user.current_blog!=nil
		if !@blog
			return redirect_to new_blog_path
		end
		#purge empty posts
		@blog.posts.each do |p|
			if p.user==current_user && p.empty?
				p.destroy
			end
		end

		#refresh blog
		@blog.reload
	end

	def edit
		#need to be logged in for this one

		#me 
		@user = current_user

		#all blogs one collaborates on
		@allRoles = current_user.all_roles

		#active / current blog
		if current_user.current_blog!=nil
			@blog = current_user.current_blog  
			@myRole = @user.get_role @blog
			@role = @blog.roles.new
			@allUsers = @blog.roles.all
		end
	end

	private
	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
	  params.require(:user).permit(:first_name, :last_name, :about, :email, :password, :password_confirmation)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_bubbles.html.erb
<% n=0 %>
<% (users).first(14).each do |u| %>
  	<% n=n+1 %>
  		<%= link_to u do %>
  			<%= image_tag u.gravatar_url, :class=> "gravatar-"+(size ? size : "med" )+" wiggler has_tooltip", :data=>{:placement=> "right", :html => true}, :title=> u.full_name+" <br><span class='small' style='color: #c0c0c0'> #{u.all_roles.count } Blogs / #{u.posts.count} Posts  </div>" %>
  		<% end %>
  		<% if n%break_at==0 %>
			<div></div>
		<% end %>
<% end %>

app/views/users/edit.html.erb
<div class='floatBox'>
<h1>Settings</h1>
<%= render partial: 'layouts/flash' %>
<div class="dropdown dd-loadBlog">

<button class='btn btn-primary' data-toggle='dropdown'>
	<% if @blog %>
	<span data-saver-sync='edit_blog_title'><%= @blog.title%> </span>
	<% else %>
		<i> No active Blog</i>
	<% end %>
	<span class='caret'></span></button>
	  <ul class="dropdown-menu pull-right" role="menu2">
	  	<% @allRoles.each do |r| %>
	  		<% if !@blog || r.blog_id != @blog.id %>
	  		<li><%= link_to r.blog.title,  load_blog_path(r.blog_id), :method => :patch %></li>
	  		<% end %>
	  	<% end %>
	  	<li class='divider'></li>
	  	<li><%= link_to "Create New", new_blog_path %></li>
	  </ul>
</div>


<!-- Nav tabs -->
<ul id='settingsTabs' class="nav nav-tabs" role="tablist">
<% if @blog %>
  <li><a href="#blogInfo" role="tab" data-toggle="tab">Blog Info</a></li>
  <li><a href="#users" role="tab" data-toggle="tab">Users</a></li>
 <% end %>
  <li><a href="#profile" role="tab" data-toggle="tab">My Profile</a></li>
<% if @current_user.has_open_invites? %>
   <li>  
        <div class='open_invites_badge' class='open_invites_badge'> <%= @current_user.open_invites_count %></div>
        <a style='padding-right: 30px' href="#invites" role="tab" data-toggle="tab">Invites</a>
    </li>
  <% end %>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<% if @blog %>
  <!-- blog info --> 
  <div class="tab-pane" id="blogInfo">
  	<p><br/>You are a <em><%= @current_user.current_role_text %></em> on this blog.
      <% if !@current_user.is_creator? %>
      Click  <%= link_to "here", blog_role_path(@blog.id, @myRole.id), :method => :delete, data: { confirm: 'Are you sure?' } %> to leave the blog.
      <br/> <br/>
      <% else %>
      Click <%= link_to "here", blog_path(@blog.id), :method => :delete, data: { confirm: 'This will remove the blog, as well as associated member roles and posts. Are you sure?' } %> to delete blog.
      <% end %>
      </p>
     <% if @current_user.current_role == Role::CREATOR %> 
    	<%= form_for @blog, remote: true, :html => {:role => "form"} do |f| %>	
      	 <div class="form-group">
        <%= f.text_field :title, :class => "bigger", :placeholder => @current_user.first_name+"'s blog", :autocomplete => 'off' %>
    	  </div>
    	  <div class="form-group">
    	    <%= f.text_area :description, :class => "autosize smaller", :placeholder => "Description",  :autocomplete => 'off'%>
    	  </div>
      	<% end %>
        <% else %>
            <div style='width: 300px; margin:0px auto'>
    <p class='bigger'><%= @blog.title %></p>
    <p class='smaller'><%= @blog.description %></p>
    </div>

    <% end %>
  </div>

  <!-- users in blog --> 
  <div class="tab-pane" id="users">
    <% if @current_user.current_role > Role::CONTRIBUTOR %> 
    	<%= form_for [@blog, @role], remote: true, :data => { :success_callback => "addUserSuccess"}, :html => {:role => "form"} do |f| %>	
      	<%= render partial: 'layouts/form_error', locals: {:_model => @role} %>
      	 <div class="form-group">
          <span id='newuser_role' class='<%= "disabled" if !@current_user.is_creator? %> has_tooltip' title='Invite as Collaborator. <%= "Click to change." if @current_user.is_creator? %>'  style='position: relative; '>
            <span class='newuser_moderator' style='position: absolute; top: -2px; font-size:8px; font-weight: bold; left:-8px; display: none'>M</span>
        		<span class='icon btn-inline glyphicon glyphicon-user' style='margin-top: 8px; margin-right: 15px'>
            </span>
          </span>
          <%= f.hidden_field :role, :value => 0,  :autocomplete => 'off', :data => {:noAutoSubmit => true }  %>
           <%= f.text_field :email, :placeholder => "Enter Email", :autocomplete => 'off', :data => {:noAutoSubmit => true }  %>

      		<%= f.submit "+", :class => "btn btn-primary btn-inline icon" %>

      	</div> 
    	<% end %>
    <% end %>
    <div class='users_table'>
      <table>
        <% @allUsers.order([:active, :role]).reverse.each do |u| %>
            <tr class='<%= Role::STATUS_TEXT[u.active].downcase  %>' <%= "style='font-weight: bold'".html_safe if (u.user && is_current?(u.user))  %> >
              <td >
                  <% if is_current? u.user %>
                      <%= image_tag  @current_user.gravatar_url, :class => "gravatar_sm"  %> 
                 <% else %>
                    <%= image_tag  User::gravatar_url(u.email||u.user.email), :class => "gravatar_sm" if u.email||u.user.email %> 
                  <% end %>

                <% userName =  u.user ? is_current?(u.user) ? "You" : u.user.full_name : @current_user.is_creator? ? u.email : u.email.split("@")[0]+"@ ... " %> 
                <%= !u.user ? userName : link_to(userName, u.user, :class => "nolink", :target => "_blank") %>
               <% if @current_user.can_edit_role?(u) && !is_current?(u.user) %>
                <%= link_to "", blog_role_path(@blog.id, u.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'icon delete_icon glyphicon glyphicon-remove' %>
               <% end %>
              </td>
              <td>
                <span class='role_name'><%= Role::ROLE_TEXT[u.role] %> </span>

                <% if @current_user.can_edit_role?(u) && !is_current?(u.user) %>
                  <%= form_for [@blog, u], remote: true, :data => { :success_callback => "changeRoleSuccess"}, :html => { :role => "form"}  do |f| %>
                  <%= f.hidden_field :role,  :autocomplete => 'off'  %>
                  <span class='changeRole_icon icon glyphicon glyphicon-wrench'></span>
                  <% end %>
                <% end %> </td>
              <td>
               <% if @current_user.can_edit_role?(u) && u.active==0 %>
                  <span class='zeroClipboard glyphicon glyphicon-paperclip has_tooltip' title='Copy Invite URL to clipboard' data-clipboard-text='<%= invite_url (u.token) %>'></span>
               <% end %>
                <i><%= Role::STATUS_TEXT[u.active] %></i>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>


 <% end %>
  <!-- profile --> 
  <div class="tab-pane" id="profile">
  	<%= image_tag @current_user.gravatar_url, :class => 'gravatar has_tooltip wiggler', :data => {:placement => "right"} ,:title => "Change profile image via gravatar.com." %>
  	<%= form_for @current_user, :url => user_path(@current_user.id), remote: true,  :html => {:role => "form"} do |f| %>	
  	 <div class="form-group">
    <%= f.text_field :first_name, :placeholder => "First Name", :autocomplete => 'off' %>
	  </div>
	  <div class="form-group">
	    <%= f.text_field :last_name, :placeholder => "Last Name",   :autocomplete => 'off'%>
	  </div>
	  <div class="form-group">
	    <%= f.text_area :about, :class => "autosize smaller", :placeholder => "A little bit about me..",   :autocomplete => 'off'%>
	  </div>
  	<% end %>
  </div>

  <!-- invites -->
  <% if @current_user.has_open_invites? %>
   <div class="tab-pane" id="invites">
    <p>
      <br/>
      You have <%= @current_user.open_invites_count %> open <%= "invite".pluralize @current_user.open_invites_count %>.
      </p> 

       <div >
      <table class='invites-table'>
        <% @current_user.open_invites.each do |i| %>
            <tr class='<%= Role::STATUS_TEXT[i.active].downcase  %>'>
              <td><%=  image_tag  i.blog.user.gravatar_url, :class => "gravatar_sm" %> <b><%= i.blog.user.first_name.capitalize %></b> invites you to be a <b><%= Role::ROLE_TEXT[i.role] %></b> on '<%=i.blog.title %>'  </td>
              <td>
                     <%= link_to "", accept_invite_path(i.token), :class=>"icon glyphicon glyphicon-ok has_tooltip", :title =>"Join" %>
                     <%= form_for i, url: deny_invite_path(i.token), :html => {:class => "inline"} do |f| %>
                      <%= f.hidden_field :active, value: -1 %>
                      <span class="icon glyphicon glyphicon-remove has_tooltip" title ="Deny" data-input='submit' ></span>
                     <% end %>
                </td>
            </tr>
        <% end %>
      </table>
    </div>

   </div>
  <% end %>

</div>
</div>

app/views/users/index.html.erb
<div class='floatBox'>
	<div style='width: 550px; margin: 0px auto;'>
	<%= render partial: "users/user_bubbles", locals: {users: @users, size: "lrg", break_at: 7 } %>
	</div>
</div>

<%= content_for :in_header do %>
<br/>
<b> All the Bloggers!</b>
<% end %>

app/views/users/my_posts.html.erb
<div class='floatBox'>
	<% if @blog %>
	<h1><%= @blog.title %> : Posts</h1>
	<%= link_to  "Add a Post", new_blog_post_path(@blog.id), :class=>"btn btn-primary" %>
	<%= render partial: 'layouts/flash' %>
	<% else %>
	<h1>Whoops, we can't find your blog!</h1>
	<p> You currently don't have a current blog set. Set your blog in the config or <%= link_to "Create a new blog", blogs_new_path %>.</p>
	<% end %>
	
	<% if @blog && !@blog.posts.empty? %>
	<table class='posts'>
		<thead>
		<tr>
			<th>
				Title
			</th>
			<th>
				Author
			</th>
			<th>
				Date
			</th>
		</tr>
		</thead>
		<tbody>
			<% @blog.posts.order(:id).reverse.each do |p| %>
				<% if p.published || p.user==@current_user || @current_user.can_edit_post?(p) %>
					<tr class='post_item'>
						<td style='position: relative'>
							
							<% if !p.published %>
								<span class='draft_label'>Draft</span>
							<% end %>

							<%= (@current_user.can_edit_post?(p)) ? link_to(p.title,  edit_blog_post_path(@blog.id, p.id)) : p.title %> 
							<% if @current_user.can_edit_post? p %> 
							<%= link_to "", blog_post_path(@blog.id, p.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'icon delete_icon glyphicon glyphicon-remove has_tooltip', :title=>"Delete Post" %>
							<% end %>
							<% if p.published %> 
								<%= link_to "", [@blog, p], :class => 'icon glyphicon glyphicon-new-window has_tooltip',:target=>"_blank", :title=>"view post" %>
							<% end %>
							
						</td>
						<td>
							<%= link_to p.user.first_name+" "+p.user.last_name, p.user, :class => 'nolink has_tooltip', :title => p.user.first_name+" is a "+ (p.author_role ? Role::ROLE_TEXT[p.author_role.role] : "Nonmember")%> 
						</td>
						<td style='vertical-align: middle'>
							<i style='font-size: 10px; color: #a3a3a3'>Updated <%= (time_ago_in_words p.updated_at) + " ago" %></i>
							<br/><%=  p.created_at.strftime("%F") %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
		
	</table>
	<% else %>
	<br><br>
	<p><i>Currently There are no posts!</i></p>
	<% end %>

</div>

app/views/users/new.html.erb
<div class='floatBox'>
<h1>Wanna Register?</h1>
<%= render partial: 'layouts/flash' %>

<%= form_for @user, :html => {:role => "form"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :first_name, :placeholder => "First Name", :autocomplete => 'off' %>
  </div>
  <div class="form-group">
    <%= f.text_field :last_name, :placeholder => "Last Name",  :autocomplete => 'off'%>
  </div>
  <div class="form-group">
    <%= f.text_field :email, :placeholder => "Email", :autocomplete => 'off', :value=>@email %>
  </div>
  <div class="form-group">
    <%= f.password_field :password,  :placeholder => "Password"%>
  </div>
    <div class="form-group">
    <%= f.password_field :password_confirmation, :placeholder => "Confirm Your Password"  %>
  </div>
  <div class="form-group">
    <%= f.submit "Sign Up", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class='floatBox'>
	<%= image_tag @user.gravatar_url, :class=> "gravatar-lrg" %>
	<h1><%= @user.full_name.titleize %></h1>
	<p>
		<%= auto_link simple_format @user.about %>
	</p>
	<br/><br/>
	<div class='user_blogs_wpr'>
		<% n = 0 %>
		<% @user.roles.each do |r| %>
		<% n=n+1 %>
			<%= link_to r.blog, :class=>'blog_circle nolink has_tooltip wiggler '+r.get_role_text.downcase,:data=>{:html => true, :placement=>"bottom"}, :title=> "<b>"+@user.first_name+"</b> is a <b>"+r.get_role_text+"</b> for <i>"+r.blog.title+"</i>.<p class='blog_descrip'> "+r.blog.description+"</p>" do %>
				<span><%= r.blog.title %></span>
			<% end %>
			<% if n%5==0 %>
				<div></div>
			<% end %>

		<% end %>
	</div>
</div>