config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/pages/home"
  get "/about" =>  "pages#about", as: :about
   get "/help" =>  "pages#help", as: :help

  get "/my-posts" => "users#my_posts", as: :my_posts
  patch "/load-blog/:id" => "users#load_blog", as: :load_blog
  get "/invite/:id" => "roles#show", as: :invite
  patch "/invite/:id/deny" => "roles#deny_invite", as: :deny_invite
  get "/invite/:id/accept" => "roles#accept_invite", as: :accept_invite
  get "/register" => "users#new", as: :register
  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create", as: :sessions
  get "/config" => "users#edit", as: :config
  post "blogs/:blog_id/roles/:id"   => "roles#update"
  patch "/password_resets/:id/edit" => "password_resets#update", as: :password_reset

  resources :sessions, only: [:new, :create]
  resources :users, only: [:create, :index, :update, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :blogs do
    resources :roles, only: [:new, :show, :update, :create, :destroy]
    resources :posts
  end

end

app/views/pages/_help_diagrams.html.erb
<div class='feature'>
	<div class='gif'>
		<%= image_tag "menu.gif" %>
	</div>
	<h4> Navigation</h4>
	<p>
	O..hey takes advantage of the <b>corners as hotspots</b> for navigation and other goodies. To use main menu, hover your mouse in the <b>top right corner</b>. This will give you option to login, register, and etc.
	</p>
</p>
</div>

<div class='feature'>
	<div class='gif'>
		
		<%= image_tag "editposts.gif" %>
	</div>
	<h4> Creating/Editing post </h4>

	<p>
	When creating/editing post, as soon as you type something, O..hey will save it as a draft..you can see the <b>post options</b> and also publish it by hovering in <b>lower left corner</b> and clicking the <span class='glyphicon glyphicon-cog'></span> icon. This will also have keyboard shortcuts for the edit page.
	</p>
	<p>
		The <b>lower right corner</b> will contain  a simple button to <b>return you to the posts</b> page.
	</p>
</div>

	<div class='feature'>
		<div class='gif'>
			<%= image_tag "settings.gif" %>
		</div>
		<h4> Settings </h4>
		<p> 
		In the settings panel, you can switch between current blogs, add users, accept or deny invites, as well as edit your info. To "switch"  blogs click on the <b>top button</b>, and <b>choose a different blog</b> or <b>create one</b>.
		</p>
	</div>

app/views/pages/about.html.erb
<div class='floatBox'>
<h1>About</h1>
<p> 
	O..hey is a simple blogging platform built with rails, as a test.  It was created by <a href='http://chris-malcolm.com'>Chris Malcolm</a>.
</p>
<p>
	It features automatic ajax-saving posts and changes, multi-user support with ability to invite moderators and collaborators, and multiple-blog support. The design ui is also an experiment, with a suddle use of corner "hotspots" as means of hiding less-used content. 
</p>
<p>
	<a href='http://github.com/cjm771/ohey'>Github</a>

</div>

app/views/pages/help.html.erb
<div class='floatBox'>
<h1>Help</h1>
<%= render partial: "pages/help_diagrams" %>
</div>

app/views/pages/home.html.erb
<div id='homePage' class='floatBox'>
<div id='splash'>
	<%= render partial: 'layouts/flash' %>

	<h1><span id='typer'></span></h1>

	<div id='register_button' class='btn btn-lg btn-primary'> Try it now!</div>
</div>


</div>
<div class='content' >
	<div class='slide'>
	<h1> How to Use</h1>
	<%= render partial: "pages/help_diagrams" %>
	</div>


	<div class='slide' style='width: 550px;'>
		<h1> Meet some Bloggers</h1>
		<p> As a user, not only can you create your own blogs..but you can also be invited as a collaborator or moderator on other people's blogs!
		 <%= link_to "View All Users..", users_path %>
		</p>
		<br/><br/>
			<%= render partial: "users/user_bubbles", locals: {users: @users, size: "med", break_at: 9} %>
	</div>


	<div class='slide'>

	<h1> Discover Some Blogs</h1>
		<p>Check out some blogs. 	
			<%= link_to "View All Blogs..", blogs_path %>
		<br/><br/></p>
		<%= render partial: "blogs/blogs_masonry", locals: {blogs: @blogs, amount: 3} %>
	</div>


	<div class='slide'>
		<h1>  Latest Posts</h1>
		<p>The latest posts this site has to offer. <br/><br/></p>
		<div class='masonry'>
			<% n = 0 %>
			<% @posts.each do |b| %>
			<% n=n+1 %>
				<%= link_to [b.blog, b], :class=>"nolink" do %>
				<div class='wiggler box box<%= (@posts.count-n)%4==0 ? 2 : 1%> color<%=rand(0..3) %>'>
					<div class='box_wpr'>
						<p style='opacity: .5' class='small'><i>Posted <%= time_ago_in_words b.created_at %></i></p>
						<h4><%= b.title %></h4>
						<p class='small'>
							<%= truncate(strip_tags(b.description),:length=>100) %>
						</p>
						<div style='opacity: .9'>
						<%= image_tag b.user.gravatar_url, :class=> "gravatar_xs " %>
						<%= "<b>#{b.user.first_name}</b> for <i>#{b.blog.title}</i>".html_safe %>
						</div>
					</div>
				</div>
				<% end%>
			<% end %>
		</div>
	</div>
	<%= render partial: "layouts/footer" %>
</div>