config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/pages/home"
  get "/about" =>  "pages#about", as: :about
   get "/help" =>  "pages#help", as: :help

  get "/my-posts" => "users#my_posts", as: :my_posts
  patch "/load-blog/:id" => "users#load_blog", as: :load_blog
  get "/invite/:id" => "roles#show", as: :invite
  patch "/invite/:id/deny" => "roles#deny_invite", as: :deny_invite
  get "/invite/:id/accept" => "roles#accept_invite", as: :accept_invite
  get "/register" => "users#new", as: :register
  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create", as: :sessions
  get "/config" => "users#edit", as: :config
  post "blogs/:blog_id/roles/:id"   => "roles#update"
  patch "/password_resets/:id/edit" => "password_resets#update", as: :password_reset

  resources :sessions, only: [:new, :create]
  resources :users, only: [:create, :index, :update, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :blogs do
    resources :roles, only: [:new, :show, :update, :create, :destroy]
    resources :posts
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
<div class='flash <%= type %>'>
	<%= message %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='footer'>
	&copy 2014 <a href='http://chris-malcolm.com'>Chris Malcolm</a>
</div>

app/views/layouts/_form_error.html.erb
<% if _model.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(_model.errors.count, "error") %> prohibited this <%= _message %></h2>

  <ul>
  <% _model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>O..hey. | <%= controller.controller_name.capitalize %> | <%= controller.action_name.capitalize %></title>
<link href="//fonts.googleapis.com/css?family=Source+Sans Pro:200italic,200,300italic,300,400italic,400,600italic,600,700italic,700,900italic,900" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name+"_"+controller.action_name %> <%= yield :body_class %>">
	<div id='menu'>
		<div id='menu_wpr' data-intro='Hover here for menu options!'>
			<% if !logged_in? %>
			<%= link_to "Home", root_path %>
			<%= link_to "Help", help_path %>
			<%= link_to "About", about_path %>
			<%= link_to "Login", login_path %>
			<%= link_to "Register", register_path %>
			<% else %>
			<% if @current_user.has_open_invites? %>
				<%= link_to  @current_user.open_invites_count, config_path+"#invites",
					 :data => {:placement => :bottom},
					 :title => "You have #{@current_user.open_invites_count} open #{"invite".pluralize  @current_user.open_invites_count }",
					 :class => "has_tooltip open_invites_badge" 
				%>
			<% end %>
			<%= link_to @current_user, :class=> "nolink_extreme" do %>
				<%= image_tag @current_user.gravatar_url, :class => "gravatar", :title => "Hi, #{@current_user.first_name}!" %>
			<% end %>
			<span class='menu_icon' data-toggle='dropdown'> &#9776;</span>
			  <ul class="dropdown-menu pull-right" role="menu">
			  	<li><%= link_to "Profile", @current_user %></li>
			    <% if @current_user.current_blog_id && @current_user.current_blog %>
			    	<li><%= link_to "My Blog", @current_user.current_blog %></li>
			   		<li><%= link_to "My Posts", my_posts_path %></li>
			    	<li><%= link_to "New Post", new_blog_post_path(@current_user.current_blog.id) %>
			    <% else %>
			    	<li><%= link_to "Create blog", new_blog_path %></li>
			    <% end %>
			    </li>
			    
			    <li><%= link_to "Settings", config_path %></li>
			      <li class="divider"></li>
			       <li><%= link_to "Home", root_path %></li>
			        <li><%= link_to "Help", help_path %></li>
			         <li><%= link_to "About", about_path %></li>
			    <li class="divider"></li>
			    	<li><%= link_to "Logout", logout_path,  method: :delete %></li>
			  </ul>
			<% end %>
		</div>
	</div>


<div id='container'>
	<div class='drawer left'>
		<div class='drawer_wpr'>
		<%= yield :left_drawer %>
		
		</div>

	</div>
	<div class='main'>
		<div id='header'>
			<%= link_to "O..hey.", root_path, :class=>'header_text nolink' %>
			<%= yield :in_header %>
		</div>
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/layouts/user_mailer.text.erb
Hey <%= @user ?  "#{@user.first_name.capitalize}," : "!" %>

<%= yield %>


Much Love,
The O..Hey team